### ISSUE TITLE
Add horizontal scrolling option

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#22]
It would perform the same as the vertical with the pages continuously scrolling to the side.

Not high priority, but could be a nice feature for users.

**Comment by kjantzer** [comment]
Hmm, I was assuming `UICollectionView` had a horizontal scrolling setting, but I guess I was thinking of `UIPageViewController`.

http://stackoverflow.com/a/19435898/484780

**Comment by hebertialmeida** [comment]
Yes `UICollectionView` works horizontally.

**Comment by hebertialmeida** [comment]
@kjantzer Any updates on this?

**Comment by kjantzer** [comment]
@hebertialmeida - No, had move on to some other projects.

**Comment by danfsd** [comment]
Since [Safari 7.0](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_7_0.html) and the UIWebview are able to paginate content into **columns** without the use of any custom javascript or CSS . I made horizontal scrolling work, but still need to integrate with other components of the framework (such as the Sidepanel, etc).

**Comment by hebertialmeida** [comment]
@danfsd Interesting because I will start working on this, where is your implementation, maybe I can create a branch for that so we can work together to finish that, I did Som implementation for side panel..

**Comment by danfsd** [comment]
@hebertialmeida it's on my forked version, on the branch `horizontal-scroll`.

[Horizontal Scroll branch](https://github.com/danfsd/FolioReaderKit/tree/horizontal-scroll)

It still needs some work to be done:
- When swiping back between `FolioReaderPage`, we need to change the horizontal offset of the scrollview to the last page.
- Strange behavior when running on landscape mode
- Fix `FolioReaderSidepanel` anchors to move horizontally instead of vertical

**Comment by hebertialmeida** [comment]
Cool! I have created a branch, so you can make a PR and we can work together on this. https://github.com/FolioReader/FolioReaderKit/tree/horizontal-scroll

**Comment by hebertialmeida** [comment]
TODO:
- [x] A config that allow init on specific orientation and enable or not orientation switch.
- [ ] If allowed user should be able to switch the orientation inside the reader, probably from Fonts menu.
- [ ] Redesign Table of Contents and icons on left menu.

Bugs:
- [ ] Fix device rotation to keep same page;
- [ ] When horizontal if playing audio it do not change page automatically.

**Comment by hebertialmeida** [comment]
Guys I want you opinion on issue #88
