### ISSUE TITLE
Will FolioReaderKit support Swift 4.0?

### ISSUE THREAD

**Issue by litt1e-p** [FolioReader/FolioReaderKit#263]
thanks for your great FolioReaderKit firstly, and will it support Swift 4?

**Comment by mayooresan** [comment]
Wondering the same! 👍

**Comment by hebertialmeida** [comment]
Yeah, it will, but I have not started yet

**Comment by odunsair** [comment]
Hi @hebertialmeida, We're still waiting.

**Comment by wedranb** [comment]
Hi, thanks for creating this amazing reader/parser!

It would be nice if you create some plan for refactoring so that we can help.

Cheers! :)

**Comment by hebertialmeida** [comment]
@wedranb Hey, yeah I will need help on that, the first step is to fully fix it for iOS 11 and iPhone X, then migrate to swift 4.

There is a discussion here https://github.com/FolioReader/FolioReaderKit/issues/261 and also https://github.com/FolioReader/FolioReaderKit/pull/270 that is going on. We definitely need help because I think the ideal implementation is to use the new safe layout guides.

**Comment by odunsair** [comment]
Hi, thanks for this library!
How is going Swift 4 support update ? @hebertialmeida

**Comment by hebertialmeida** [comment]
The swift 4 support is in the master branch.
