### ISSUE TITLE
Highlight across paragraphs Bug

### ISSUE THREAD

**Issue by pklarl** [FolioReader/FolioReaderKit#315]
Hi guys,

creating highlights across paragraphs leads to the following bugs ([Video Highlight Paragraph](https://youtu.be/ZUOC6dfe9kw)):

1. The text is not marked correctly and the HTML is "destroyed".
2. After changing to another chapter and calling up the highlight via the menu, the passage is found in the ePub but not marked.
3. In some cases the upper menu can not be opened afterwards (restart of the app is necessary)
4. After restarting the app, opening the highlight via the menu will not open the right passage in the ePub.

Tables are similar or even worse ([Video Highlight Table](https://youtu.be/XWk45EJn3yU)). Other readers do not have these problems. We use the current version of FolioReader 1.3.0. 
Is the problem known, and if so, is there a (foreseeable) solution?

Many Thanks
Peter

**Comment by pklarl** [comment]
Then problem is known. Is a solution foreseeable here ... this problem is really serious.

**Comment by hebertialmeida** [comment]
Yes, this is a known bug since #37 there is a discussion there. but, it is a complex thing in my point of view. Because we should not simply implement a new solution but try to migrate the existing ones.

On #37 we have discussed implementing it using Rangy. Android version has this already implemented. Probably it is possible to reuse the same concept and it will work between platforms. I don't really have time to work on this right now but I would love to see a pull request on this.

Do you think you can fix it? Many people will be benefited from that.

Android implementation:
https://github.com/FolioReader/FolioReader-Android/blob/master/sample/src/main/assets/highlights/highlights_data.json
https://github.com/FolioReader/FolioReader-Android/blob/master/folioreader/src/main/java/com/folioreader/util/HighlightUtil.java
https://github.com/FolioReader/FolioReader-Android/search?utf8=✓&q=rangy

**Comment by pklarl** [comment]
Thanks for the interesting hint. That sounds great. Our app developer will take look at it and contact you to work with you.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
