### ISSUE TITLE
The last version o cocoapods not support for Objc?

### ISSUE THREAD

**Issue by lucasromanomr** [FolioReader/FolioReaderKit#323]
I was looking at the last version that is in the cocoapods, and I saw that there are some methods that are not working on objc, example of this is the present that is not visible.

**Comment by hebertialmeida** [comment]
To be honest I haven't tried that in a while. In the past, it was working but as I am focused on Swift for couple years I just don't test that.

Which methods are not working? Are you able to list them or even open a pull request with that?

**Comment by lucasromanomr** [comment]
I was looking and as main classes are not giving support:
`FolioReaderConfig` and` FolioReader`

I think I may have a few more, initially what I saw was just these, because that was what was initially implemented

**Comment by onivem** [comment]
@hebertialmeida @lucasromanomr I'm having the similar issue, methods and properties are not visible from Objective-C. The reason is missing @objc annotation.
So that
`open var shouldHideNavigationOnTap = true`
should become:
`@objc open var shouldHideNavigationOnTap = true`
The reason is Swift 4 does not automatically imply that NSObject classes are accessible to Objective-C. Please check the following article:
https://useyourloaf.com/blog/objc-warnings-upgrading-to-swift-4/

**Comment by lucasromanomr** [comment]
@onivem that is, it lacks the adequacy so that the objc exergue both the parameters and methods

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
