### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by mythodeia** [FolioReader/FolioReaderKit#39]
Great lib. thanks for sharing. :+1: 
i get a crash when i do this:
open the app and tap the top book. The swipe right to expose the close button and tap it.
Tap to reopen the same book. Crash occurs. Check screen below

![screen](https://cloud.githubusercontent.com/assets/1748458/12371799/b4745cde-bc48-11e5-8119-ff5d7ac48510.png)

on an iPhone 6S Plus device when i do the above scenario it works fine but i get this in the console:
```
Error Domain=NSCocoaErrorDomain Code=513 "“The Silver Chair.epub” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/var/mobile/Containers/Bundle/Application/7029A818-8BBB-454D-A4FD-D20F2B146B07/Example.app/The Silver Chair.epub, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x137b22450 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```

**Comment by hebertialmeida** [comment]
Hey @mythodeia, this is not really a bug, on the reader but it is a lack of options there is an issue #20 related to this.

On simulator the problem is that by default Folio Reader removes the original ePub file after the unzip process and when you are trying to open on second time the file doesn't exists. On device there is a error on removing this because on sample example the ePub file is on App directory, and you don't have permission to remove a file from this directory, that's why it works and throw a error.

O a real scenario usually the ePub files will be downloaded from a server to /Documents directory, so it works perfectly.

What I'm planning to do on issue #20 is to add a option on config to remove or not the original ePub from disk.

**Comment by lakshayasachdeva1990** [comment]
Hebert need ur help on this, pls reply at lkshsachdeva@gmail.com

**Comment by mythodeia** [comment]
@hebertialmeida :+1: thanks for your response.
