### ISSUE TITLE
Please update to Swift 2.0

### ISSUE THREAD

**Issue by real1900** [FolioReader/FolioReaderKit#4]

**Comment by Huluhu** [comment]
update to Swift 2.0?

**Comment by hebertialmeida** [comment]
@real1900 @Huluhu  Hey guys, good news, I'm working on this and a lot of improvements.

I will try to release it soon.

**Comment by Huluhu** [comment]
GREAT!

**Comment by hebertialmeida** [comment]
@Huluhu @real1900 The code is updated to Swift 2

**Comment by Huluhu** [comment]
Thank you! But I got some error message:

The file “Pods.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/HULI/Desktop/FolioReaderKit-master/Example/Pods/Target Support Files/Pods/Pods.debug.xcconfig)
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.


Do I need to turn on some settings before I can play it?

**Comment by hebertialmeida** [comment]
Now I have implemented Cocoapods. Run 'pod install'.

**Comment by Huluhu** [comment]
I have run the pod install in terminal, but I got this: /Users/Hu/Desktop/FolioReaderKit-master/Source/FolioReaderFontsMenu.swift:10:8: No such module 'TGPControls'

**Comment by hebertialmeida** [comment]
Yes, it's a but... I had problems with TGPControls so I fixed and submitted a Pull Request, it's accepted but now they need to update podspec.

I have just pushed a new commit to master branch with a fix, download it.

**Comment by Huluhu** [comment]
That's been fixed. But but when compile Example.xcodeproj, i still got /Users/Hu/Desktop/FolioReaderKit-master/Example/Example/ViewController.swift:10:8: No such module 'FolioReaderKit' . Should I manually add the framework?

**Comment by hebertialmeida** [comment]
Do you have to build using the Example.xcworkspace



Heberti Almeida
iOS Developer & UI Designer
