### ISSUE TITLE
Text to Speech support

### ISSUE THREAD

**Issue by hunght** [FolioReader/FolioReaderKit#53]
i want to make this feature, but i'm new in swift and don't know how to detect, highlight a sentence on webview, could someone tell me how to do it. thanks for great work

**Comment by kjantzer** [comment]
"Text to speak" - are you thinking of using the phones default "computer voice"?

@hunght I would suggest looking at part of the framework that already does text selection for highlighting

**Comment by hebertialmeida** [comment]
@hunght If you can implement this I will assign it to you.

There is a text highlighting feature for audio player, also the audio player is already working for Media Overlays, it should probably be simple to reuse. If you have problem maybe @kjantzer can help you, because he implemented this feature.

I think TTS will only make sense if there is no Media Overlays, so take a look on this implementation. https://github.com/FolioReader/FolioReaderKit/blob/master/Source/FolioReaderAudioPlayer.swift
https://github.com/FolioReader/FolioReaderKit/blob/master/Source/FolioReaderPlayerMenu.swift
https://github.com/FolioReader/FolioReaderKit/blob/master/Source/EPUBCore/FRSmilElement.swift
https://github.com/FolioReader/FolioReaderKit/blob/master/Source/EPUBCore/FRSmils.swift

**Comment by hunght** [comment]
@hebertialmeida thanks you, i 'm finishing this feature, pls assign this to me

**Comment by hebertialmeida** [comment]
@hunght You can branch from master, then make a PR to master, I can review an test before merge.
