### ISSUE TITLE
Crash in readTOCReference

### ISSUE THREAD

**Issue by ProudOfZiggy** [FolioReader/FolioReaderKit#63]
FREpubParser.swift at 226 row

let toc = FRTocReference(title: label, resource: resource!, fragmentID: fragmentID)

It crashes because **resource** variable is nil after:
let href = hrefSplit[0]
let resource = book.resources.getByHref(href)

**href** variable is "Text/part4.xhtml"

It seem method **getByHref:** return nil while trying to find appropriate resource in dictionary (return resources[href]).

Here is a book I'm trying https://www.dropbox.com/s/vpam1fu4v42lsyj/9781556501302.epub?dl=0

Working good in iBooks.

P.S. I'll be very appreciated if you download this book and tell me, so I could remove this from public access. 

P.P.S. Maybe safe unwrapping of optional **resource** will be enough? =)

**Comment by hebertialmeida** [comment]
I have downloaded it, and I will test.

**Comment by hebertialmeida** [comment]
@ProudOfZiggy Actually it is not working perfect on iBooks, the book is parsed but do you can not navigate using the table of contents. Sometimes iBooks throw an alert and closes the book:
![img_6511](https://cloud.githubusercontent.com/assets/103670/14785415/076d0b62-0ad1-11e6-84b9-9b72689182c4.PNG)

What I did is to deal with optional resource, so the book will open normally, same as iBooks do, but when do you open the Table of contents menu and tap on it I print this log error:
![screen shot 2016-04-25 at 10 35 20 am](https://cloud.githubusercontent.com/assets/103670/14785510/82b24ff8-0ad1-11e6-999b-c39d95ca01d2.png)

Maybe instead of printing on console I should throw an alert for user.

**Comment by hebertialmeida** [comment]
Just pushed a new update with fixes.

**Comment by ProudOfZiggy** [comment]
Well, I was trying this book in iBooks on Mac. It woking great.

I made my own fix for your reader. I succesufull opened a book I gave you. Then I compared this book in iBooks (Mac) and in Folio reader, no pages/chapters was lost bacause of my fix. My fix is just skipping nil resources, I think iBooks on Mac works the same way.

**Comment by hebertialmeida** [comment]
I have tested on iBooks Mac, same it open but the Table of Content do not redirect to the right page.
